version: "3"
services:
  ruoyi-mysql:
    image: mysql:5.7
    container_name: ruoyi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    # 对外端口:容器端口
    ports:
      - "6060:3306"
    network_mode: bridge

  ruoyi-redis:
    image: redis
    container_name: ruoyi-redis
    # 对外端口:容器端口
    ports:
      - "6161:6379"
    network_mode: bridge

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    user: root
    # 对外端口:容器端口
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jenkins-compose:/var/jenkins_home
      - /www/ssl:/ssl # 添加这一行
    network_mode: bridge
    container_name: jenkins
