version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    environment:
      MYSQL_ROOT_PASSWORD: "gxh123456"
    # 对外端口:容器端口
    ports:
      - "3306:3306"
    network_mode: bridge

  redis:
    image: redis
    container_name: redis
    environment:
      REDIS_PASSWORD: "gxh123456"
    ports:
      - "6379:6379"
    network_mode: bridge

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    user: root
    # 对外端口:容器端口
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jenkins-compose:/var/jenkins_home
    network_mode: bridge
    container_name: jenkins
