version: '1'

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "6262:80"
    volumes:
      - /www/conf:/etc/nginx/conf.d
      - /www/web:/www/web
    network_mode: bridge
    container_name: ruoyi-nginx
