version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'gxh123456'
    # 对外端口:容器端口
    ports:
      - '3306:3306'
    network_mode: bridge
    restart: always # 设置启动策略为 always

  redis:
    image: redis
    container_name: redis
    environment:
      REDIS_PASSWORD: 'gxh123456'
    # 对外端口:容器端口
    ports:
      - '6379:6379'
    network_mode: bridge
    restart: always # 设置启动策略为 always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    environment:
      JAVA_OPTS: '-Djava.awt.headless=true'
    # 对外端口:容器端口
    ports:
      - '8888:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jenkins-compose:/var/jenkins_home
    network_mode: bridge
    restart: always # 设置启动策略为 always

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: 'admin'
      MINIO_SECRET_KEY: 'admin123'
      TZ: 'Asia/Shanghai'
    command: server /data --console-address ":9090" --address ":9000"
    # 对外端口:容器端口
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - /home/docker/minio/data:/data
    network_mode: bridge
    restart: always # 设置启动策略为 always
